controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\Clients;
use app\models\Frends;
use app\models\User;
use Faker\Provider\cs_CZ\DateTime;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\Town;
use app\models\Users;
use app\models\Gender;  
use app\models\Friends;
use app\models\ClientsTest;
use app\models\Clients2;

class SiteController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionTowns()
    {
      $table = new Town();
        
        return $this->render('towns',[
            'datas' => $table->getTown(),
            'label' => 'Сортовано по id',
        ]);
    }
    public function actionPeoples()
    {
        
        $table = new Town();
        return $this->render('towns', [
            'datas' => $table->sortPeoples(),
            'label' => 'Сортовано по кількості населення',
        ]);
    }
    public function actionSort_towns()
    {
        $table = new Town();
        return $this->render('towns',[
           'datas' => $table->sortTowns(),
           'label' => 'Сортовано по місту в алфавітному порядку',
        ]);
    }
    public function actionPager()
    {
        $pager = new Town();
        $pager->pager($countries, $pagination);
        return $this->render('pager', [
            'countries' => $countries,
            'pagination' => $pagination,
        ]);

    }
    public function processor(){

    }

    public function actionFriends()
    {
        $users = new Users();
        $gender = new Gender(); 
        $friends_list = new Friends();
        $test_friend = $friends_list->getAllFriends();

        $object_users = $friends_list->arrayUsers(); //list all users
        $array_users = array();
        $array_friends = array();
        // create associative array in array with count friends to current user
        foreach ($object_users as $object_user) {
            array_push($array_users,  ["user" => $object_user->user_id,
                                    "is_friends" => $friends_list->countFriends($object_user->user_id)]);

        }
//        $name_friends = $friends_list->nameFriends(1);
//        $friends_list->proccesor();
//create friends object $array_friends
        foreach ($object_users as $object_user) {
            $temp_users = $friends_list->nameFriends($object_user->user_id);
            $prepare_users = $friends_list->processor($temp_users);

            array_push($array_friends, $prepare_users);
        }
        
        return $this->render('friends',[
            'users' => $users->getUsers(),
            'genders' =>  $gender->getGender(),
            'friends' => $friends_list->getFriends(),
            'all_friends' => $test_friend,
            'count_friends' => $array_users,
            'array_friends' => $array_friends
        ]);
    }
    public function actionForm()
    {
        $table = new Town();

        $request  = Yii::$app->request;
        $country = $request->post('country');
        $town = $request->post('town');
        $peoples = $request->post('peoples');
        $table->saveForm($country, $town, $peoples);

        return $this->redirect(Yii::$app->request->referrer);
        
    }
    public function actionDelete($id)
    {
        $delete = new Users();
        $delete->deleteUser($id);
        return $this->redirect(Yii::$app->request->referrer);
    }
    public function actionEdit($id)
    {

    }

    public function actionUser()
    {
        $table = new Users();

        $request  = Yii::$app->request;
        $name =     $request->post('name');
        $gender =     $request->post('gender');
        $age =  $request->post('age');

        $table->saveNewUser($name, $gender, $age);

        return $this->redirect(Yii::$app->request->referrer);
    }
    public function actionUpdate_u()
    {
        $table = new Users();

        $request  = Yii::$app->request;
        $id =       $request->post('id');
        $name =     $request->post('name');
        $gender =     $request->post('gender');
        $age =  $request->post('age');
        $friends=   $request->post('friends');
        $gender_select = $request->post('status_gender');
//        var_dump($gender_select);die();
        $table->updateUser($id, $name, $gender, $age);

        return $this->redirect(Yii::$app->request->referrer);

    }

    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    public function actionAbout()
    {
        return $this->render('about');
    }


    public function actionParse()
    {
        function dayDifference($data)
        {
            $time = strtotime($data);
            $today = time();
            $day = ($today - $time)/86400;
            $day = floor($day);
            return $day;
        }
        
        $amount = '';
        $date = '';
        $email = '';

        if (file_exists("../web/files/new25052016.txt"))
            echo "File exist.";
        else
            echo "File not find";
        echo '</br>';
        echo filesize("../web/files/new25052016.txt")/1000 . 'Кб';
        echo '</br></br>';
        $clients = new Clients2();
        if (file_exists("../web/files/new25052016.txt")) {
            $handle = fopen("../web/files/new25052016.txt", "r"); // Открываем файл в режиме чтения
            while (!feof($handle)) {
                $buffer = (string)fgetss($handle);
//                echo $buffer.'<br>';

                $results = explode(" ", $buffer);
                foreach ($results as $key => $result) {
                    switch ($key){
                        case 0 : $amount = $result; break;
                        case 1 : $date = $result; break;
                        case 2 : $email = $result; break;
                        default: break;
                    }
                    echo $result . '</br>';
                }
                $clients->SaveClients2($amount, $date, $email, dayDifference($date));

            }

            fclose($handle);

        }


    }
}

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textArea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/friends.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;
use yii\helpers\ArrayHelper;
use app\models\Gender;
use yii\bootstrap\modal;
use yii\bootstrap\Dropdown;
//var_dump($array_friends);die();
//function var_object($var) {
//    static $int=0;
//    echo '<pre><b style="background: red;padding: 1px 5px;">'.$int.'</b> ';
//    var_export($var);
//    echo '</pre>';
//    $int++;
//    die();
//}
//var_object($array_friends);die();

$this->title = 'Друзі';
function getModal($user)
    {
        Modal::begin([
            'size' => 'modal-lg',
            'header' => '<h2>Редагувати</h2>',
            'toggleButton' => [
                'label' => 'Редагувати',
                'tag' => 'button',
                'class' => 'btn btn-warning',
            ],
            'footer' => ''
        ]);
        ?>
        <table>
            <thead>
                <tr>
                    <th>Ім'я</th>
                    <th>Стать</th>
                    <th>Вік</th>
                </tr>
            </thead>
            <tbody>
            <?= Html::beginForm(['site/update_u', 'user' => $user], 'post', ['enctype' => 'multipart/form-data']) ?>
                <tr>
                    <td style="display: none">
                        <?= Html::input('text',     'id',     $user->id,['class' => '']) ?>
                    </td>
                    <td>
                        <?= Html::input('text',     'name',     $user->name,['class' => '']) ?>
                    </td>
                    <td>
                        <?= Html::dropDownList('gender', null,
                            ArrayHelper::map(Gender::find('name')->all(), 'id', 'name_gender')) ?>
                    </td>
                    <td>
                        <?= Html::input('number',   'age',      $user->age,['class' => '']) ?>
                    </td>
                </tr>
            </tbody>
        </table>
        <?= Html::submitButton('Зберегти', ['class' => 'btn btn-primary']); ?>
        <?= Html::endForm(); ?>
        <?php Modal::end(); ?>
<?php
        return null;
   }
?>
<h2><span class="label label-default">Соціальна мережа</span></h2>
<!--All data in table is attached to object User for id user-->
<table class="table">
    <thead>
        <tr>
            <th>Ім'я</th>
            <th>Стать</th>
            <th>Вік</th>
            <th>Друзі</th>
            <th>Друзі</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($users as $key => $user): ?>
            <tr>
                <td id="<?= $user->id ?>" class="users"><?=$user->name ?></td>
                <td><?=$genders[$user->gender_id-1]->name_gender ?></td>
                <td><?=$user->age?></td>
                <td><?= Html::submitButton('Друзі', ['class' => 'btn btn-default contacts', 'id' => $user->id,
                        'data-target' => "#myModalContacts", 'data-toggle' => "modal",
                        'data-toggle' => 'tooltip', 'title' => 'Керувати контактами моїх друзів'])?></td>
                <td>
                    <div class="dropdown" id="<?= $user->id ?>">
                        <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">
                            <span class="caret"></span></button>
                        <ul class="dropdown-menu">
                           <li><a href="#"></a></li>
                        </ul>
                    </div>
                </td>
                <td>
                    <?= getModal($user); ?>

                </td>
                <td>
                    <a href="<?=Url::to(['site/delete', 'id' => $user->id]) ?>"><?= Html::submitButton('Видалити', ['class' => 'btn btn-danger']) ?></a>
                </td>
            </tr>

        <?php endforeach; ?>
<!--        add user-->
        <?= Html::beginForm(['site/user', 'user' => $user], 'post', ['enctype' => 'multipart/form-data']) ?>
        <td>
            <?= Html::input('text',     'name',     '',['class' => $town]) ?>
        </td>
        <td >
            <?= Html::dropDownList('gender', null,
                ArrayHelper::map(Gender::find('name')->all(), 'id', 'name_gender')) ?>
        </td>
        <td>
            <?= Html::input('number',   'age',      '',['class' => $town]) ?>
        </td>
    </tbody>
    </table>
    <div class="form-group">
        <?= Html::submitButton('Додати', ['class' => 'btn btn-primary', 'data-toggle' => 'tooltip', 'title' => 'Зберегти дані нового користувача' ]) ?>
    </div>
    <?= Html::endForm() ?>

<div class="modal fade" id="myModalContacts" role="dialog">
    <div class="modal-dialog modal-sm">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Коло моїх друзів</h4>
            </div>
            <div class="modal-body">
                <li class="list-group-item list-group-item-info active" id="user">-
                </li>
                <?php  foreach($users as $user):?>
                    <li class="list-group-item list-group-item-info" id="f_category">
                        <?= $user->name ?>
                        <input id="<?= $user->id ?>" class="checked_friends" type="checkbox" />
                    </li>
                <?php   endforeach; ?>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Вийти</button>
            </div>

        </div>

    </div>
</div>
<!--    <button href="#" data-toggle="tooltip" title="Hooray!">Hover over me</button>-->

<?php
// create tooltip
$script = <<< JS
  $(document).ready(function(){
            $('[data-toggle="tooltip"]').tooltip();
            
        });
JS;

$this->registerJs($script);



?>

<?php
$this->registerJsFile('/web/js/set_friends.js', ['depends' => [\yii\web\JqueryAsset::className()]]);
?>

views/site/index.php
<?php

/* @var $this yii\web\View */

$this->title = 'My Yii Application';
?>
<div class="site-index">

    <div class="jumbotron">
        <h1>Congratulations!</h1>

        <p class="lead">You have successfully created your Yii-powered application.</p>

        <p><a class="btn btn-lg btn-success" href="http://www.yiiframework.com">Get started with Yii</a></p>
    </div>

    <div class="body-content">

        <div class="row">
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/doc/">Yii Documentation &raquo;</a></p>
            </div>
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/forum/">Yii Forum &raquo;</a></p>
            </div>
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/extensions/">Yii Extensions &raquo;</a></p>
            </div>
        </div>

    </div>
</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'options' => ['class' => 'form-horizontal'],
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

    <div class="col-lg-offset-1" style="color:#999;">
        You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>
        To modify the username/password, please check out the code <code>app\models\User::$users</code>.
    </div>
</div>

views/site/pager.php
<?php
use yii\helpers\Html;
use yii\widgets\LinkPager;
?>
    <h1>Міста</h1>
    <ul>
        <?php foreach ($countries as $country): ?>
            <li>
                <?= Html::encode("{$country->name_town} (id: {$country->id})") ?>:
                <?= $country->country ?>
            </li>
        <?php endforeach; ?>
    </ul>

<?= LinkPager::widget(['pagination' => $pagination]) ?>

views/site/towns.php
<?php
use yii\helpers\Url;
use yii\widgets\Menu;
use yii\helpers\Html;
//var_dump($datas);die();
$this->title = 'Міста';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1 class="towns">Міста</h1>
    <div class="row">
    <div class="col-sm-6">
        <nav class="navbar ">
        <div class="container-fluid">
            <ul class="nav navbar-nav ">
                <li><a href="<?= Url::to(['site/towns'])?>">Сортувати по: id</a></li>
                <li><a href="<?= Url::to(['site/sort_towns'])?>">Сортувати по: місту</a></li>
                <li><a href="<?= Url::to(['site/peoples'])?>">Сортувати по: кількості жителів</a></li>
            </ul>
        </div>
        </nav>
        <?php
        echo Menu::widget([
            'items' => [
                ['label' => 'Сортувати по: id',                     'url' => ['site/towns']],
                ['label' => 'Сортувати по: місту',                  'url' => ['site/sort_towns']],
                ['label' => 'Сортувати по: кількості жителів', 'url' => ['site/peoples']],

            ],
        ]);
        ?>
        <p>
            <?= Html::a('Сортувати по: id', ['site/towns'], ['class' => 'profile-link']) ?>
        </p>
        <label  class="label label-pill label-default"><?= $label?></label>
    </div>
    <div class="col-sm-6">
        <?= Html::img('@web/images/ukraine.jpg', ['alt' => 'Наша Україна'])?>
    </div>
        <table class="table">
            <thead>
            <tr>
                <th>Країна</th>
                <th>Місто</th>
                <th>Проживає людей</th>
            </tr>
            </thead>

            <tbody>
            <?php foreach ($datas as $data):?>
                <tr>
                    <td>
                        <?=$data->country?>
                    </td>
                    <td>
                        <?=$data->name_town?>
                    </td>
                    <td>
                        <?=$data->peaples?>
                    </td>
                </tr>
            <?php endforeach;?>
            <tr>
                <?= Html::beginForm(['site/form', 'town' => $town], 'post', ['enctype' => 'multipart/form-data']) ?>
                <td>
                    <?= Html::input('text', 'country', $town->name, ['class' => $town]) ?>
                </td>
                <td>
                    <?= Html::input('text', 'town', $town->town, ['class' => $town]) ?>
                </td>
                <td>
                    <?= Html::input('number', 'peoples', $town->peoples, ['class' => $town]) ?>
                </td>

            </tr>
            </tbody>
        </table>
        <?= Html::submitButton('Додати', ['class' => 'btn btn-primary']) ?>
        <?= Html::endForm() ?>
</div>